#!/bin/bash

grep -e '<td>.\+<\/td>' | sed 's/^[^<]*>//g' | \
sed 's/<[^>]*>//g' | sed 's/^\([^,]*\),\([^,]*\)/\1\n\2/g' | \
sed 's/^[[:space:]]*//g' | tr '[:upper:]' '[:lower:]' | \
sed "s/\`/\'/g" | grep -e "^[pk\'mnwlhaeiou[:space:]]\+$" | \
sed -e "s/[ ]\([a-z']\+\)/\n\1/g" |  sed -e "s/\r//g" | sort -u 
